# Generated by Django 5.0.6 on 2024-05-26 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_address_userprofile_and_more'),
        ('posts', '0002_rename_user_bookmark_owner_rename_user_comment_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.userprofile'),
        ),
    ]
