# Generated by Django 5.0.6 on 2024-05-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Post Media'),
        ),
    ]
