# Generated by Django 5.0.6 on 2024-06-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='owner',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='owner',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='owner',
            new_name='author',
        ),
    ]
