# Generated by Django 5.0.6 on 2024-06-07 07:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_alter_address_owner_alter_follower_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.TimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.TimeField(auto_now=True, verbose_name='Updated_at')),
                ('media', models.FileField(blank=True, null=True, upload_to='media/event', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi'])], verbose_name='Event Media')),
                ('capacity', models.IntegerField(verbose_name="Event's capacity")),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Event', to='accounts.userprofile')),
            ],
        ),
    ]
