# Generated by Django 5.0.6 on 2024-06-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='creator',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
    ]
