# Generated by Django 5.0.6 on 2024-06-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_creator_event_author_remove_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
