# Generated by Django 5.0.6 on 2024-06-25 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_address'),
        ('posts', '0011_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
        migrations.AddField(
            model_name='event',
            name='bookmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_bookmarks', to='posts.bookmark'),
        ),
        migrations.AddField(
            model_name='event',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_comments', to='posts.comment'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event End Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Event End Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_form_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Event Form URL'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event Start Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Event Start Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Is Online'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_physical',
            field=models.BooleanField(default=False, verbose_name='Is Physical'),
        ),
        migrations.AddField(
            model_name='event',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_likes', to='posts.like'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Venue'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
    ]
