# Generated by Django 5.0.6 on 2024-06-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_capacity_event_bookmark_event_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='event',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='event',
            name='like',
        ),
    ]
