# Generated by Django 5.0.6 on 2024-06-07 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_application_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/Job_Media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi'])], verbose_name='Job Media'),
        ),
    ]
