# Generated by Django 5.0.6 on 2024-07-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_job_owner_job_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='job_description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='job',
            name='application_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Application Link'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_qualifications',
            field=models.TextField(blank=True, null=True, verbose_name='Qualifications'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_skills',
            field=models.TextField(blank=True, null=True, verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_title',
            field=models.CharField(default='Default Job Title', max_length=255, verbose_name='Job Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('online', 'Online'), ('physical', 'Physical'), ('both', 'Both')], default='physical', help_text='Select the type of job (Online, Physical, or Both).', max_length=10, verbose_name='Job Type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created '),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
