# Generated by Django 5.0.6 on 2024-07-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_company_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('online', 'online'), ('physical', 'physical'), ('both', 'both')], default='physical', help_text='Select the type of job (Online, Physical, or Both).', max_length=10, verbose_name='Job Type'),
        ),
    ]
