# Generated by Django 5.0.6 on 2024-05-21 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_superset_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='education',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_education', to='accounts.userprofile'),
        ),
    ]
