# Generated by Django 5.0.6 on 2024-05-26 12:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_county_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='userprofile',
        ),
        migrations.RemoveField(
            model_name='education',
            name='userprofile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education',
        ),
        migrations.AddField(
            model_name='address',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='accounts.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='accounts.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
