# Generated by Django 5.0.6 on 2024-06-10 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_address_owner_alter_follower_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='owner',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_address', to='accounts.address'),
        ),
    ]
