# Generated by Django 5.0.6 on 2024-05-30 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_support_delete_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='Supporter',
            new_name='Owner',
        ),
    ]
