# Generated by Django 5.0.6 on 2024-05-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_rename_supporter_support_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='Owner',
            new_name='owner',
        ),
    ]
