# Generated by Django 5.0.6 on 2024-06-03 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_userprofile_profile_picture'),
        ('support', '0005_alter_support_amount_alter_support_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='support',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='support',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='support',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='support',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
