# Generated by Django 5.0.6 on 2024-06-07 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_alter_support_amount_alter_support_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/support_Media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi'])], verbose_name='Support Media'),
        ),
    ]
