# Generated by Django 5.0.6 on 2024-05-31 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Announcement Title')),
                ('content', models.TextField(verbose_name='Announcement contents')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('media', models.ImageField(blank=True, null=True, upload_to='announcements', verbose_name='Announcement Media')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='accounts.userprofile')),
            ],
        ),
    ]
