# Generated by Django 5.0.6 on 2024-06-10 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/event', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi'])], verbose_name='Event Media'),
        ),
    ]
